// <auto-generated />
using Infrastructure.Common.Persistence;
using Infrastructure.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ScootersDbContext), typeof(ScootersDbContextModel))]
