// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Infrastructure.CompiledModels
{
    public partial class ScootersDbContextModel
    {
        private ScootersDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("77dea3ff-31e6-495c-821a-60b860273a01"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var coordinates = CoordinatesEntityType.Create(this);
            var reservation = ReservationEntityType.Create(this);
            var ride = RideEntityType.Create(this);
            var scooter = ScooterEntityType.Create(this);
            var user = UserEntityType.Create(this);

            CoordinatesEntityType.CreateForeignKey1(coordinates, scooter);
            ReservationEntityType.CreateForeignKey1(reservation, scooter);
            ReservationEntityType.CreateForeignKey2(reservation, user);
            RideEntityType.CreateForeignKey1(ride, scooter);
            RideEntityType.CreateForeignKey2(ride, user);

            CoordinatesEntityType.CreateAnnotations(coordinates);
            ReservationEntityType.CreateAnnotations(reservation);
            RideEntityType.CreateAnnotations(ride);
            ScooterEntityType.CreateAnnotations(scooter);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "9.0.3");
        }
    }
}
